# Generated by Django 4.2.4 on 2023-08-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='invite_code',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
