# Generated by Django 4.2.4 on 2023-08-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_api', '0002_alter_profile_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
